use crate::repo::Repository;
use crate::Error;

impl Repository {
    /// Create a new commit that reverts the changes of `commit_id`. The new
    /// commit message is generated by Git in non-interactive mode.
    /// Conflicts are surfaced by the worktree status; exit code 1 from git
    /// revert is accepted so the conflict state is visible.
    pub fn revert_commit(&self, commit_id: &str) -> Result<(), Error> {
        let commit_id = validate_commit_id(commit_id)?;
        let _ = self.git(&["rev-parse", "--verify", commit_id])?;
        let _ = self.git_allowing_exit_codes(&["revert", "--no-edit", commit_id], &[1])?;
        Ok(())
    }
}

fn validate_commit_id(commit_id: &str) -> Result<&str, Error> {
    let commit_id = commit_id.trim();
    if commit_id.is_empty() || commit_id.starts_with('-') {
        return Err(Error::InvalidCommit(commit_id.to_string()));
    }
    Ok(commit_id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_helpers::*;

    #[test]
    fn revert_commit_creates_inverse_commit_on_current_branch() {
        let repo_dir = TempRepo::init_with_commit("revert-create-inverse");
        repo_dir.write("file.txt", "second\n");
        repo_dir.git(&["add", "file.txt"]);
        repo_dir.git(&["commit", "-m", "second"]);

        let target = {
            let repo = Repository::open(&repo_dir.path).unwrap();
            repo.list_commits(1).unwrap()[0].id.clone()
        };

        let repo = Repository::open(&repo_dir.path).unwrap();
        repo.revert_commit(&target).unwrap();

        let subjects = repo_dir.git_output(&["log", "--format=%s"]);
        assert!(subjects.contains("Revert \"second\""));
        let contents = std::fs::read_to_string(repo_dir.path.join("file.txt")).unwrap();
        assert_eq!(contents, "initial\n");
    }

    #[test]
    fn revert_commit_rejects_invalid_commit_id() {
        let repo_dir = TempRepo::init_with_commit("revert-invalid");
        let repo = Repository::open(&repo_dir.path).unwrap();

        let err = repo.revert_commit("  ").unwrap_err();
        assert!(matches!(err, Error::InvalidCommit(_)));

        let err = repo.revert_commit("-bad").unwrap_err();
        assert!(matches!(err, Error::InvalidCommit(_)));
    }
}
